global using Microsoft.Maui;
global using Microsoft.Maui.Controls;
global using Microsoft.Maui.Controls.Hosting;
global using Microsoft.Maui.Hosting;
global using System;
global using System.Collections.ObjectModel;
global using System.Diagnostics;
global using System.Linq;
global using System.Threading.Tasks;
